"""add_revoked_jwt_tokens_table

Revision ID: 38835278f821
Revises: 023d1f5cfb6d
Create Date: 2026-02-26 06:44:09.944266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38835278f821'
down_revision = '023d1f5cfb6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delete_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
