"""Add condition field to item model

Revision ID: d1ef2e0a7209
Revises: 57f2fcb6d886
Create Date: 2026-02-16 14:29:17.271892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ef2e0a7209'
down_revision = '57f2fcb6d886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('condition')

    # ### end Alembic commands ###
